package adeveloperdiary.testpromotion;

/**
 * This class was automatically generated by the data modeler tool.
 */

import java.util.Date;


public class Period extends BaseElement {
    private Date desidedStartDate;
    private SeasonType seasonType;

    public Period() {
    }

    public Date getDesidedStartDate() {
        return desidedStartDate;
    }

    public void setDesidedStartDate(Date desidedStartDate) {
        this.desidedStartDate = desidedStartDate;
    }

    public SeasonType getSeasonType() {
        return seasonType;
    }

    public void setSeasonType(SeasonType seasonType) {
        this.seasonType = seasonType;
    }

    @Override
    public String toString() {
        final StringBuffer sb = new StringBuffer("Period{");
        sb.append("desidedStartDate=").append(desidedStartDate);
        sb.append(", seasonType=").append(seasonType);
        sb.append('}');
        return sb.toString();
    }
}
