package adeveloperdiary.testpromotion;

/**
 * This class was automatically generated by the data modeler tool.
 */

public enum SeasonType {
    day, week, weekend, month, summer, winter, spring, autumn, fullYear
}
